### ISSUE TITLE
 Create a Single Actor Page Component

### ISSUE THREAD

**Issue by farouk26** [202306-NEA-DZ-FEW/movie-project-devsquad#11]
(Develop a Single Actor Page which displays the information about the current actor , this page contains the following : 

- [x] Actor's picture
- [x] Actor name
- [x] Gender
- [x] Popularity
- [x] Birthday
- [x] Biography
- [x] [BONUS] - List of movies the actor participated in.
- [x] Additional informations or Style are Optional

**Comment by mouloud247** [comment]
Working on it

**Comment by farouk26** [comment]
Tasks complete
