### ISSUE TITLE
Develop fetching Functions & Data handlings

### ISSUE THREAD

**Issue by farouk26** [202306-NEA-DZ-FEW/movie-project-devsquad#12]
- [x] Create a utils file

- [x]  Inside the utils file develop all functions that are responsible for API requests as well as handling different data types. these functions will play a role on interacting with the API throughout the whole project

- [x]   Ensure their functionality

- [x]  Use proper variable names for an easier code readability

**Comment by takidilmi** [comment]
working on it

**Comment by hasnahadd** [comment]
working on it ....

**Comment by farouk26** [comment]
**Tasks Complete**
