### ISSUE TITLE
 Create a Navbar Component

### ISSUE THREAD

**Issue by farouk26** [202306-NEA-DZ-FEW/movie-project-devsquad#5]
Navbar component should include a Navbar.jsx file inside it, the file should contain the following : 

- [x] Navbar that shows up on all pages

- [x] Logo of the website 

- [x] Navbar items with dropdown menus (**Genres** (**includes the genres of all movies**) in the dropdown & **Movies** ( contains ["Top Rate", "Popular", "Latest", "Now playing", "Upcoming"] in the dropdown) and finally **Actors**

- [x] Navbar items Functionality :  

> (Clicking on Action movies for example takes us to a movies page displaying Action movies) 

> (Clicking on the Actors Navbar item takes us to actors page and shows us a list of all popular actors.)

- [x] Search box (or Search Icon) where you can type the movie's or actor's name and it displays the related results.

**Comment by hasnahadd** [comment]
working on it .....

**Comment by farouk26** [comment]
Tasks Complete
