### ISSUE TITLE
 Create a Single Movie Component

### ISSUE THREAD

**Issue by farouk26** [202306-NEA-DZ-FEW/movie-project-devsquad#9]
(Develop a Single Movie Page , responsible for displaying a current movie details , this page should contain the following  :

- [x] The movie poster
- [x] The movie title
- [x] Release date
- [x] Runtime
- [x] Movie's Language
- [x] The movie rating and how many votes has it received
- [x] Director's name
- [x] Overview of the movie
- [x] The main 5 actors of the movies in the credit section
- [x] A related movies section which includes at least five related movies
- [x] A trailer section that has the movie trailer from youtube
- [x] The movie production company name and logo
- [x] Ensure Functionality , for example : 

> Clicking an actor in the 5 main actors should take you to the single actor page

> Clicking on a movie in the related movies section should take you to the Single movie page

**Comment by mounibzaidi** [comment]
started working on it
